# Customize the prompt
[prompt]
format = "[$username]($style) in [$directory]($style) $ "
# No newline before the prompt
add_newline = false
# List of modules to display in the prompt
order = [
  "line_break",
  "username",
  "hostname",
  "directory",
  "git_branch",
  "git_commit",
  "git_state",
  "git_status",
  "cmd_duration",
  "line_break",
  "jobs",
  "battery",
  "character"
]
# Enable transient prompt
transient_prompt = true

# Line break module configuration
[line_break]
disabled = false

# Character module configuration
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# Command duration module configuration
[cmd_duration]
min_time = 2000 # Show command duration only if it exceeds 2 seconds
show_milliseconds = true

# Directory module configuration
[directory]
truncate_to_repo = true

# Username module configuration
[username]
disabled = true

# Hostname module configuration
[hostname]
disabled = true

# Battery module configuration
[battery]
disabled = true
