# No newline before the prompt
add_newline = false

# Line break module configuration
[line_break]
disabled = false

# Character module configuration
[character]
success_symbol = '[  ](bold green)'
error_symbol = '[✘](bold red)'
vimcmd_symbol = '[ 󰰒](bold green)' 
vimcmd_visual_symbol = '[  ](bold green)'

# Command duration module configuration
[cmd_duration]
min_time = 2000 # Show command duration only if it exceeds 2 seconds
show_milliseconds = true

# Directory module configuration
[directory]
truncation_length = 3
truncation_symbol = '󰇘 '
truncate_to_repo = true
format = '[$path]($style)[$read_only]($read_only_style) '
read_only = '🔒'
read_only_style = 'red'
home_symbol = '󰟐 '

# Username module configuration
[username]
style_user = 'white bold'
style_root = 'white bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Hostname module configuration
[hostname]
ssh_only = true
ssh_symbol = '󰣀'
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
disabled = false

# Git branch module configuration
[git_branch]
symbol = " "  
truncation_length = 64
truncation_symbol = '…'
only_attached = false

[memory_usage]
disabled = false
threshold = -1
symbol = '󰍛 '
style = 'bold dimmed lightred'
