live_config_reload = true

[shell]
program = "/bin/fish"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "Full"
opacity = 0.92
blur = true
startup_mode = "Windowed"
title = "blackbeard os"
dynamic_title = false

[scrolling]
history = 5000

[font]
size = 14
normal.family = "Hurmit Nerd Font"
bold.family = "Hurmit Nerd Font"
italic.family = "Hurmit Nerd Font"

# Colors
## Default colors
[colors.primary]
background = '#2B2D42'
foreground = '#5AF78E'  # Green

## Cursor colors
[colors.cursor]
text = '#2B2D42'
cursor = '#5AF78E'  # Green

## Selection colors
[colors.selection]
text = '#2B2D42'
background = '#DFFAF8'

## Normal colors
[colors.normal]
black   = '#4B0082'
red     = '#483D8B'
green   = '#6A5ACD'
yellow  = '#7B68EE'
blue    = '#9370DB'
magenta = '#8A2BE2'
cyan    = '#7F00FF'
white   = '#D8BFD8'

## Bright colors
[colors.bright]
black   = '#9400D3'
red     = '#8A2BE2'
green   = '#7B68EE'
yellow  = '#6A5ACD'
blue    = '#483D8B'
magenta = '#4B0082'
cyan    = '#7F00FF'
white   = '#D8BFD8'

[mouse]
hide_when_typing = true
