# Alacritty Colors and Font Configuration
[terminal.shell]
program = "/bin/fish"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "Full"
opacity = 0.93
blur = true
dynamic_title = false

[scrolling]
history = 5000

[font]
size = 24  # Configurable font size
normal.family = "Hurmit Nerd Font"
bold.family = "Hurmit Nerd Font"
italic.family = "Hurmit Nerd Font"

[colors]
[colors.primary]
background = "#1C1B1A"
foreground = "#F4E3C1"

[colors.cursor]
text = "#F27835"
cursor = "#F27835"

[colors.selection]
text = "#1C1B1A"
background = "#F4A259"

[colors.normal]
black = "#454240"
red = "#D13438"
green = "#73A857"
yellow = "#F1C232"
blue = "#5A8CA5"
magenta = "#A066C9"
cyan = "#46B9A0"
white = "#AA9E87"

[colors.bright]
black = "#614A4D"
red = "#FF5F56"
green = "#88C070"
yellow = "#FADF60"
blue = "#73B3D8"
magenta = "#B794F4"
cyan = "#6FE2CA"
white = "#F6E8CD"
