
[terminal.shell]
program = "/bin/fish"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "Full"
opacity = 0.92
blur = true
startup_mode = "Windowed"
title = "blackbeard os"
dynamic_title = false

[scrolling]
history = 5000

[font]
size = 20
normal.family = "Hurmit Nerd Font"
bold.family = "Hurmit Nerd Font"
italic.family = "Hurmit Nerd Font"

# Colors
## Default colors
[colors.primary]
background = '#262626'
foreground = '#F0EAD6'  # Text color

## Cursor colors
[colors.cursor]
text = '#262626'
cursor = '#5AF78E'  # Green

## Selection colors
[colors.selection]
text = '#0FEFB0'
background = '#4974A5' ## highlight color

## Normal colors
[colors.normal]
black = '#000000'
red = '#FF2800'
green = '#33FF33'  
yellow = '#E5FF33'
blue = '#6D90CB'
magenta = '#CC00CC'
cyan = '#007F7F'
white = '#F0EAD6'

## Bright colors
[colors.bright]
black = '#000000'
red = '#FF2800'
green = '#00FF00'
yellow = '#DFFF00'
blue = '#6281B6'
magenta = '#C55FCC'
cyan = '#00FFFF'
white = '#FFFFFF'

[mouse]
hide_when_typing = true

[general]
live_config_reload = true

[terminal]
