[terminal.shell]
program = "/bin/fish"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "Full"
opacity = 0.96
blur = true
startup_mode = "Windowed"
title = "blackbeard os"
dynamic_title = false

[scrolling]
history = 5000

[font]
size = 12
normal.family = "Hurmit Nerd Font"
bold.family = "Hurmit Nerd Font"
italic.family = "Hurmit Nerd Font"

# Colors
## Default colors
[colors.primary]
background = '#1C1B1A'  # Deep retro brown
foreground = '#F4E3C1'  # Warm retro cream

## Cursor colors
[colors.cursor]
text = '#1C1B1A'        # Matches background
cursor = '#F27835'      # Retro orange

## Selection colors
[colors.selection]
text = '#1C1B1A'        # Matches background
background = '#F4A259'  # Muted orange highlight

## Normal colors
[colors.normal]
black = '#1C1B1A'       # Deep retro brown
red = '#D13438'         # Vibrant retro red
green = '#73A857'       # Muted avocado green
blue = '#5A8CA5'        # Soft retro teal
yellow = '#F1C232'      # Golden mustard
magenta = '#A066C9'     # Soft lavender purple
cyan = '#46B9A0'        # Mint green
white = '#F4E3C1'       # Warm retro cream

## Bright colors
[colors.bright]
black = '#484441'       # Softer deep brown
red = '#FF5F56'         # Vibrant coral red
green = '#88C070'       # Bright retro lime
blue = '#73B3D8'        # Light retro teal
yellow = '#FADF60'      # Bright golden yellow
magenta = '#B794F4'     # Pastel lilac
cyan = '#6FE2CA'        # Bright aqua green
white = '#FFFFFF'       # Pure white

[mouse]
hide_when_typing = true

[general]
live_config_reload = true

[terminal]

